# Generated by Django 4.1.3 on 2022-11-03 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cerveza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estilo', models.CharField(max_length=30)),
                ('ibu', models.IntegerField(max_length=30)),
                ('alcohol', models.IntegerField(max_length=30)),
            ],
        ),
    ]
