# Generated by Django 4.1.3 on 2022-11-03 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppBirra', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minutas', models.CharField(max_length=30)),
                ('descripcion', models.CharField(max_length=30)),
                ('precio', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='cerveza',
            name='alcohol',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='cerveza',
            name='ibu',
            field=models.IntegerField(),
        ),
    ]
