# Generated by Django 4.1.2 on 2022-11-04 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppBirra', '0002_menu_alter_cerveza_alcohol_alter_cerveza_ibu'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('apellido', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=30)),
            ],
        ),
    ]
